// CAT-019: Actividades Económicas
// Catálogo oficial del Ministerio de Hacienda de El Salvador

export interface ActividadEconomica {
  codigo: string;
  descripcion: string;
}

// Catálogo completo de actividades económicas
export const actividadesEconomicas: ActividadEconomica[] = [
  { codigo: "01111", descripcion: "Cultivo de cereales (excepto arroz), legumbres y semillas oleaginosas" },
  { codigo: "01112", descripcion: "Cultivo de arroz" },
  { codigo: "01113", descripcion: "Cultivo de hortalizas, raíces y tubérculos" },
  { codigo: "01114", descripcion: "Cultivo de caña de azúcar" },
  { codigo: "01115", descripcion: "Cultivo de tabaco" },
  { codigo: "01116", descripcion: "Cultivo de plantas para fibras textiles" },
  { codigo: "01119", descripcion: "Otros cultivos transitorios n.c.p." },
  { codigo: "01121", descripcion: "Cultivo de banano" },
  { codigo: "01122", descripcion: "Cultivo de café" },
  { codigo: "01123", descripcion: "Cultivo de plantas cítricas" },
  { codigo: "01124", descripcion: "Cultivo de frutas tropicales y subtropicales" },
  { codigo: "01125", descripcion: "Cultivo de otros frutos de árboles y arbustos" },
  { codigo: "01126", descripcion: "Cultivo de frutos oleaginosos" },
  { codigo: "01127", descripcion: "Cultivo de plantas para bebidas" },
  { codigo: "01128", descripcion: "Cultivo de especias, plantas aromáticas, medicinales y farmacéuticas" },
  { codigo: "01129", descripcion: "Otros cultivos permanentes n.c.p." },
  { codigo: "01211", descripcion: "Cría de ganado bovino" },
  { codigo: "01212", descripcion: "Cría de ganado caballar y asnal" },
  { codigo: "01213", descripcion: "Cría de ganado porcino" },
  { codigo: "01214", descripcion: "Cría de aves de corral" },
  { codigo: "01215", descripcion: "Apicultura" },
  { codigo: "01216", descripcion: "Cría de otros animales n.c.p." },
  { codigo: "01221", descripcion: "Producción de leche cruda" },
  { codigo: "01222", descripcion: "Producción de huevos" },
  { codigo: "01223", descripcion: "Cria de animales para la producción de pieles y cueros" },
  { codigo: "01301", descripcion: "Actividades de apoyo a la agricultura" },
  { codigo: "01302", descripcion: "Actividades de apoyo a la ganadería" },
  { codigo: "01411", descripcion: "Explotación de bosques naturales" },
  { codigo: "01412", descripcion: "Recolección de productos forestales diferentes a la madera" },
  { codigo: "01420", descripcion: "Silvicultura y otras actividades forestales" },
  { codigo: "01501", descripcion: "Pesca marítima" },
  { codigo: "01502", descripcion: "Pesca continental" },
  { codigo: "01503", descripcion: "Acuicultura marítima" },
  { codigo: "01504", descripcion: "Acuicultura continental" },
  { codigo: "10101", descripcion: "Procesamiento y conservación de carne" },
  { codigo: "10102", descripcion: "Procesamiento y conservación de pescado, crustáceos y moluscos" },
  { codigo: "10103", descripcion: "Procesamiento y conservación de frutas y verduras" },
  { codigo: "10201", descripcion: "Fabricación de productos lácteos" },
  { codigo: "10301", descripcion: "Fabricación de productos de molinería" },
  { codigo: "10302", descripcion: "Fabricación de almidones y productos derivados del almidón" },
  { codigo: "10401", descripcion: "Fabricación de aceites y grasas de origen vegetal y animal" },
  { codigo: "10501", descripcion: "Fabricación de productos de panadería" },
  { codigo: "10611", descripcion: "Fabricación de azúcar" },
  { codigo: "10612", descripcion: "Fabricación de cacao, chocolate y productos de confitería" },
  { codigo: "10613", descripcion: "Elaboración de café, té y yerba mate" },
  { codigo: "10614", descripcion: "Fabricación de condimentos y aderezos" },
  { codigo: "10615", descripcion: "Fabricación de alimentos preparados para animales" },
  { codigo: "10711", descripcion: "Destilación, rectificación y mezcla de bebidas alcohólicas" },
  { codigo: "10712", descripcion: "Elaboración de vinos" },
  { codigo: "10713", descripcion: "Elaboración de bebidas malteadas y de malta" },
  { codigo: "10714", descripcion: "Producción de bebidas no alcohólicas; producción de aguas minerales" },
  { codigo: "11011", descripcion: "Destilación de alcohol etílico a partir de sustancias fermentadas" },
  { codigo: "11012", descripcion: "Fabricación de bebidas destiladas" },
  { codigo: "11020", descripcion: "Elaboración de vinos" },
  { codigo: "11030", descripcion: "Elaboración de bebidas fermentadas no destiladas" },
  { codigo: "11041", descripcion: "Producción de malta" },
  { codigo: "11042", descripcion: "Elaboración de cerveza" },
  { codigo: "11050", descripcion: "Elaboración de bebidas no alcohólicas y producción de aguas minerales" },
  { codigo: "12001", descripcion: "Fabricación de productos de tabaco" },
  { codigo: "13110", descripcion: "Preparación e hilatura de fibras textiles" },
  { codigo: "13120", descripcion: "Tejedura de productos textiles" },
  { codigo: "13130", descripcion: "Acabado de productos textiles" },
  { codigo: "13910", descripcion: "Fabricación de tejidos de punto y ganchillo" },
  { codigo: "13990", descripcion: "Fabricación de otros productos textiles n.c.p." },
  { codigo: "14101", descripcion: "Confección de prendas de vestir, excepto prendas de piel" },
  { codigo: "14201", descripcion: "Fabricación de artículos de piel" },
  { codigo: "14301", descripcion: "Fabricación de artículos de punto y ganchillo" },
  { codigo: "15110", descripcion: "Curtido y recurtido de cueros" },
  { codigo: "15120", descripcion: "Fabricación de calzado" },
  { codigo: "16101", descripcion: "Fabricación de papel y cartón" },
  { codigo: "17011", descripcion: "Impresión de libros, periódicos, revistas y otras publicaciones" },
  { codigo: "17012", descripcion: "Impresión de formularios continuos y otros impresos" },
  { codigo: "17020", descripcion: "Actividades de servicios relacionados con la impresión" },
  { codigo: "18110", descripcion: "Reproducción de grabaciones" },
  { codigo: "19100", descripcion: "Fabricación de productos de hornos de coque" },
  { codigo: "19201", descripcion: "Fabricación de productos de la refinación del petróleo" },
  { codigo: "20111", descripcion: "Fabricación de gases industriales" },
  { codigo: "20112", descripcion: "Fabricación de colorantes y pigmentos" },
  { codigo: "20115", descripcion: "Fabricación de fertilizantes y compuestos de nitrógeno" },
  { codigo: "20116", descripcion: "Fabricación de plásticos en formas primarias" },
  { codigo: "20121", descripcion: "Fabricación de plaguicidas y otros productos químicos de uso agropecuario" },
  { codigo: "20122", descripcion: "Fabricación de pinturas, barnices y productos de revestimiento similares" },
  { codigo: "20123", descripcion: "Fabricación de jabones y detergentes, perfumes y preparados de tocador" },
  { codigo: "20210", descripcion: "Fabricación de productos farmacéuticos de uso humano" },
  { codigo: "20220", descripcion: "Fabricación de productos farmacéuticos de uso veterinario" },
  { codigo: "21001", descripcion: "Fabricación de productos farmacéuticos, sustancias químicas medicinales" },
  { codigo: "22110", descripcion: "Fabricación de llantas y cámaras de caucho" },
  { codigo: "22190", descripcion: "Fabricación de otros productos de caucho" },
  { codigo: "22210", descripcion: "Fabricación de placas, hojas, tubos y perfiles de plástico" },
  { codigo: "22220", descripcion: "Fabricación de envases de plástico" },
  { codigo: "22290", descripcion: "Fabricación de otros artículos de plástico" },
  { codigo: "23101", descripcion: "Fabricación de vidrio y productos de vidrio" },
  { codigo: "23921", descripcion: "Fabricación de cemento, cal y yeso" },
  { codigo: "23922", descripcion: "Fabricación de artículos de hormigón, cemento y yeso" },
  { codigo: "24101", descripcion: "Industrias básicas de hierro y acero" },
  { codigo: "24210", descripcion: "Fabricación de productos primarios de metales preciosos" },
  { codigo: "24220", descripcion: "Fundición de metales" },
  { codigo: "25110", descripcion: "Fabricación de productos metálicos para uso estructural" },
  { codigo: "25120", descripcion: "Fabricación de tanques, depósitos y recipientes de metal" },
  { codigo: "25990", descripcion: "Fabricación de otros productos elaborados de metal n.c.p." },
  { codigo: "26101", descripcion: "Fabricación de componentes electrónicos" },
  { codigo: "26201", descripcion: "Fabricación de computadoras y equipo periférico" },
  { codigo: "26301", descripcion: "Fabricación de equipos de comunicación" },
  { codigo: "27110", descripcion: "Fabricación de motores, generadores y transformadores eléctricos" },
  { codigo: "27401", descripcion: "Fabricación de equipos eléctricos de iluminación" },
  { codigo: "27501", descripcion: "Fabricación de aparatos de uso doméstico" },
  { codigo: "28110", descripcion: "Fabricación de motores y turbinas" },
  { codigo: "28210", descripcion: "Fabricación de maquinaria agropecuaria y forestal" },
  { codigo: "29100", descripcion: "Fabricación de vehículos automotores" },
  { codigo: "29201", descripcion: "Fabricación de carrocerías para vehículos automotores" },
  { codigo: "29202", descripcion: "Fabricación de partes, piezas y accesorios para vehículos automotores" },
  { codigo: "30910", descripcion: "Fabricación de motocicletas" },
  { codigo: "30920", descripcion: "Fabricación de bicicletas y sillas de ruedas" },
  { codigo: "31001", descripcion: "Fabricación de muebles" },
  { codigo: "32110", descripcion: "Fabricación de joyas y artículos conexos" },
  { codigo: "32300", descripcion: "Fabricación de artículos de deporte" },
  { codigo: "32401", descripcion: "Fabricación de juegos y juguetes" },
  { codigo: "32501", descripcion: "Fabricación de instrumentos y suministros médicos y odontológicos" },
  { codigo: "32990", descripcion: "Otras industrias manufactureras n.c.p." },
  { codigo: "33110", descripcion: "Reparación de productos elaborados de metal" },
  { codigo: "33120", descripcion: "Reparación de maquinaria" },
  { codigo: "33200", descripcion: "Instalación de maquinaria y equipos industriales" },
  { codigo: "35111", descripcion: "Generación de energía eléctrica" },
  { codigo: "35112", descripcion: "Transmisión de energía eléctrica" },
  { codigo: "35113", descripcion: "Distribución de energía eléctrica" },
  { codigo: "35114", descripcion: "Comercialización de energía eléctrica" },
  { codigo: "36001", descripcion: "Captación, tratamiento y distribución de agua" },
  { codigo: "37001", descripcion: "Evacuación de aguas residuales" },
  { codigo: "38011", descripcion: "Recolección de desechos no peligrosos" },
  { codigo: "38012", descripcion: "Recolección de desechos peligrosos" },
  { codigo: "41001", descripcion: "Construcción de edificios" },
  { codigo: "42101", descripcion: "Construcción de carreteras y vías de ferrocarril" },
  { codigo: "42201", descripcion: "Construcción de proyectos de servicio público" },
  { codigo: "42901", descripcion: "Construcción de otras obras de ingeniería civil" },
  { codigo: "43110", descripcion: "Demolición" },
  { codigo: "43120", descripcion: "Preparación del terreno" },
  { codigo: "43210", descripcion: "Instalaciones eléctricas" },
  { codigo: "43220", descripcion: "Instalaciones de fontanería, calefacción y aire acondicionado" },
  { codigo: "43301", descripcion: "Terminación y acabado de edificios" },
  { codigo: "43901", descripcion: "Otras actividades especializadas para la construcción" },
  { codigo: "45111", descripcion: "Venta de automóviles y camionetas nuevos" },
  { codigo: "45112", descripcion: "Venta de automóviles y camionetas usados" },
  { codigo: "45120", descripcion: "Mantenimiento y reparación de vehículos automotores" },
  { codigo: "45130", descripcion: "Venta de partes, piezas y accesorios para vehículos automotores" },
  { codigo: "45301", descripcion: "Venta al por menor de combustible para vehículos automotores" },
  { codigo: "45401", descripcion: "Venta, mantenimiento y reparación de motocicletas" },
  { codigo: "46101", descripcion: "Venta al por mayor a cambio de una retribución o por contrato" },
  { codigo: "46201", descripcion: "Venta al por mayor de materias primas agropecuarias y animales vivos" },
  { codigo: "46311", descripcion: "Venta al por mayor de alimentos, bebidas y tabaco" },
  { codigo: "46312", descripcion: "Venta al por mayor de productos textiles, prendas de vestir y calzado" },
  { codigo: "46313", descripcion: "Venta al por mayor de productos farmacéuticos y medicinales" },
  { codigo: "46321", descripcion: "Venta al por mayor de computadoras, equipo periférico y programas" },
  { codigo: "46322", descripcion: "Venta al por mayor de equipo electrónico y de telecomunicaciones" },
  { codigo: "46323", descripcion: "Venta al por mayor de maquinaria y equipo agropecuarios" },
  { codigo: "46324", descripcion: "Venta al por mayor de maquinaria y equipo para la construcción" },
  { codigo: "47111", descripcion: "Venta al por menor en comercios no especializados (alimentos)" },
  { codigo: "47112", descripcion: "Venta al por menor en comercios no especializados (hipermercados)" },
  { codigo: "47191", descripcion: "Venta al por menor en minimercados, tiendas de barrio" },
  { codigo: "47211", descripcion: "Venta al por menor de productos agrícolas para el consumo" },
  { codigo: "47213", descripcion: "Venta al por menor de carnes, productos cárnicos y pescados" },
  { codigo: "47214", descripcion: "Venta al por menor de bebidas y productos del tabaco" },
  { codigo: "47221", descripcion: "Venta al por menor de productos farmacéuticos y medicinales" },
  { codigo: "47222", descripcion: "Venta al por menor de cosméticos, artículos de tocador y perfumería" },
  { codigo: "47301", descripcion: "Venta al por menor de combustible para vehículos automotores" },
  { codigo: "47411", descripcion: "Venta al por menor de computadoras y equipos de telecomunicaciones" },
  { codigo: "47511", descripcion: "Venta al por menor de materiales de construcción y ferretería" },
  { codigo: "47523", descripcion: "Venta al por menor de muebles para el hogar" },
  { codigo: "47611", descripcion: "Venta al por menor de libros" },
  { codigo: "47620", descripcion: "Venta al por menor de artículos deportivos" },
  { codigo: "47630", descripcion: "Venta al por menor de juegos y juguetes" },
  { codigo: "47711", descripcion: "Venta al por menor de prendas de vestir y accesorios" },
  { codigo: "47712", descripcion: "Venta al por menor de calzado y artículos de cuero" },
  { codigo: "47721", descripcion: "Venta al por menor de productos farmacéuticos" },
  { codigo: "47910", descripcion: "Venta al por menor por correo, Internet o catálogo" },
  { codigo: "47990", descripcion: "Otros tipos de venta al por menor" },
  { codigo: "49211", descripcion: "Transporte urbano y suburbano de pasajeros" },
  { codigo: "49212", descripcion: "Transporte interurbano de pasajeros" },
  { codigo: "49213", descripcion: "Transporte de pasajeros por taxis" },
  { codigo: "49221", descripcion: "Transporte de carga por carretera" },
  { codigo: "49222", descripcion: "Servicios de mudanza" },
  { codigo: "50110", descripcion: "Transporte de pasajeros marítimo y de cabotaje" },
  { codigo: "50120", descripcion: "Transporte de carga marítimo y de cabotaje" },
  { codigo: "51101", descripcion: "Transporte de pasajeros por vía aérea" },
  { codigo: "51201", descripcion: "Transporte de carga por vía aérea" },
  { codigo: "52101", descripcion: "Almacenamiento y depósito" },
  { codigo: "52211", descripcion: "Actividades de estaciones de servicio para vías férreas" },
  { codigo: "52231", descripcion: "Actividades de agencias de aduanas" },
  { codigo: "52246", descripcion: "Actividades de operadores logísticos" },
  { codigo: "53101", descripcion: "Actividades postales nacionales" },
  { codigo: "53201", descripcion: "Actividades de mensajería" },
  { codigo: "55101", descripcion: "Actividades de alojamiento en hoteles y similares" },
  { codigo: "55901", descripcion: "Otros tipos de alojamiento n.c.p." },
  { codigo: "56110", descripcion: "Actividades de restaurantes y puestos de comidas" },
  { codigo: "56120", descripcion: "Actividades de servicio móvil de comidas" },
  { codigo: "56210", descripcion: "Suministro de comidas por encargo" },
  { codigo: "56301", descripcion: "Actividades de bares y cantinas" },
  { codigo: "58110", descripcion: "Edición de libros" },
  { codigo: "58130", descripcion: "Edición de periódicos, revistas y otras publicaciones periódicas" },
  { codigo: "58201", descripcion: "Edición de programas de informática" },
  { codigo: "59111", descripcion: "Producción de películas cinematográficas y videos" },
  { codigo: "59120", descripcion: "Actividades de grabación de sonido y edición de música" },
  { codigo: "60101", descripcion: "Actividades de edición y difusión de programas de radio" },
  { codigo: "60201", descripcion: "Actividades de edición y difusión de programas de televisión" },
  { codigo: "61101", descripcion: "Actividades de telecomunicaciones alámbricas" },
  { codigo: "61201", descripcion: "Actividades de telecomunicaciones inalámbricas" },
  { codigo: "61301", descripcion: "Actividades de telecomunicación por satélite" },
  { codigo: "61901", descripcion: "Otras actividades de telecomunicaciones" },
  { codigo: "62010", descripcion: "Actividades de desarrollo de sistemas informáticos" },
  { codigo: "62020", descripcion: "Actividades de consultoría informática" },
  { codigo: "62090", descripcion: "Otras actividades de tecnologías de la información" },
  { codigo: "63111", descripcion: "Procesamiento de datos, alojamiento y actividades relacionadas" },
  { codigo: "63112", descripcion: "Portales web" },
  { codigo: "64110", descripcion: "Banco central" },
  { codigo: "64121", descripcion: "Bancos comerciales" },
  { codigo: "64122", descripcion: "Bancos de desarrollo" },
  { codigo: "64910", descripcion: "Arrendamiento financiero" },
  { codigo: "64923", descripcion: "Cooperativas de ahorro y crédito" },
  { codigo: "65111", descripcion: "Seguros de vida" },
  { codigo: "65112", descripcion: "Seguros generales" },
  { codigo: "65201", descripcion: "Actividades de administración de fondos de pensiones" },
  { codigo: "66110", descripcion: "Administración de mercados financieros" },
  { codigo: "66120", descripcion: "Actividades de intermediación de valores" },
  { codigo: "66220", descripcion: "Actividades de agentes y corredores de seguros" },
  { codigo: "68101", descripcion: "Actividades inmobiliarias con bienes propios o arrendados" },
  { codigo: "68201", descripcion: "Actividades inmobiliarias a cambio de retribución o por contrato" },
  { codigo: "69100", descripcion: "Actividades jurídicas" },
  { codigo: "69200", descripcion: "Actividades de contabilidad, teneduría de libros y auditoría" },
  { codigo: "70100", descripcion: "Actividades de administración empresarial" },
  { codigo: "70201", descripcion: "Actividades de relaciones públicas y comunicación" },
  { codigo: "70202", descripcion: "Actividades de consultoría de gestión" },
  { codigo: "71101", descripcion: "Actividades de arquitectura e ingeniería" },
  { codigo: "71201", descripcion: "Ensayos y análisis técnicos" },
  { codigo: "72100", descripcion: "Investigación y desarrollo en ciencias naturales e ingeniería" },
  { codigo: "72200", descripcion: "Investigación y desarrollo en ciencias sociales y humanidades" },
  { codigo: "73100", descripcion: "Publicidad" },
  { codigo: "73200", descripcion: "Estudios de mercado y encuestas de opinión pública" },
  { codigo: "74100", descripcion: "Actividades especializadas de diseño" },
  { codigo: "74201", descripcion: "Actividades de fotografía" },
  { codigo: "74202", descripcion: "Actividades de traducción e interpretación" },
  { codigo: "74901", descripcion: "Actividades profesionales, científicas y técnicas n.c.p." },
  { codigo: "75000", descripcion: "Actividades veterinarias" },
  { codigo: "77110", descripcion: "Alquiler de automóviles y camionetas" },
  { codigo: "77210", descripcion: "Alquiler de artículos de esparcimiento y deportivos" },
  { codigo: "77301", descripcion: "Alquiler de maquinaria y equipo agropecuario y forestal" },
  { codigo: "77302", descripcion: "Alquiler de maquinaria y equipo para la construcción" },
  { codigo: "77303", descripcion: "Alquiler de maquinaria y equipo de oficina" },
  { codigo: "78100", descripcion: "Actividades de agencias de empleo" },
  { codigo: "78200", descripcion: "Actividades de agencias de empleo temporal" },
  { codigo: "79110", descripcion: "Actividades de las agencias de viaje" },
  { codigo: "79120", descripcion: "Actividades de operadores turísticos" },
  { codigo: "80100", descripcion: "Actividades de seguridad privada" },
  { codigo: "80200", descripcion: "Actividades de servicios de sistemas de seguridad" },
  { codigo: "81100", descripcion: "Actividades combinadas de apoyo a instalaciones" },
  { codigo: "81210", descripcion: "Limpieza general interior de edificios" },
  { codigo: "81300", descripcion: "Actividades de paisajismo y servicios de mantenimiento conexos" },
  { codigo: "82110", descripcion: "Actividades combinadas de servicios administrativos de oficina" },
  { codigo: "82200", descripcion: "Actividades de centros de llamadas (call center)" },
  { codigo: "82300", descripcion: "Organización de convenciones y eventos comerciales" },
  { codigo: "82910", descripcion: "Actividades de agencias de cobro y oficinas de crédito" },
  { codigo: "82920", descripcion: "Actividades de envase y empaque" },
  { codigo: "82990", descripcion: "Otras actividades de servicio de apoyo a las empresas n.c.p." },
  { codigo: "84111", descripcion: "Actividades de la administración pública en general" },
  { codigo: "84120", descripcion: "Prestación de servicios a la comunidad en general" },
  { codigo: "84210", descripcion: "Asuntos exteriores" },
  { codigo: "84220", descripcion: "Actividades de defensa" },
  { codigo: "84230", descripcion: "Actividades de mantenimiento del orden público y de seguridad" },
  { codigo: "84300", descripcion: "Actividades de planes de seguridad social de afiliación obligatoria" },
  { codigo: "85101", descripcion: "Educación preprimaria" },
  { codigo: "85102", descripcion: "Educación primaria" },
  { codigo: "85211", descripcion: "Educación secundaria de formación general" },
  { codigo: "85212", descripcion: "Educación secundaria de formación técnica y profesional" },
  { codigo: "85300", descripcion: "Educación superior" },
  { codigo: "85410", descripcion: "Educación deportiva y recreativa" },
  { codigo: "85420", descripcion: "Educación cultural" },
  { codigo: "85501", descripcion: "Actividades de apoyo a la educación" },
  { codigo: "86101", descripcion: "Actividades de hospitales" },
  { codigo: "86201", descripcion: "Actividades de práctica médica y odontológica" },
  { codigo: "86901", descripcion: "Otras actividades de atención de la salud humana" },
  { codigo: "87010", descripcion: "Actividades de atención residencial médica" },
  { codigo: "87030", descripcion: "Actividades de atención residencial para ancianos" },
  { codigo: "87090", descripcion: "Otras actividades de atención residencial" },
  { codigo: "88000", descripcion: "Actividades de asistencia social sin alojamiento" },
  { codigo: "90001", descripcion: "Actividades de creación, artísticas y de entretenimiento" },
  { codigo: "91011", descripcion: "Actividades de bibliotecas y archivos" },
  { codigo: "91012", descripcion: "Actividades de museos, gestión de lugares históricos" },
  { codigo: "91020", descripcion: "Actividades de jardines botánicos, zoológicos y parques nacionales" },
  { codigo: "92000", descripcion: "Actividades de juegos de azar y apuestas" },
  { codigo: "93110", descripcion: "Actividades de deportes" },
  { codigo: "93120", descripcion: "Actividades de clubes deportivos" },
  { codigo: "93130", descripcion: "Actividades de gimnasios" },
  { codigo: "93210", descripcion: "Actividades de parques de atracciones y parques temáticos" },
  { codigo: "93299", descripcion: "Otras actividades de esparcimiento y recreativas n.c.p." },
  { codigo: "94110", descripcion: "Actividades de asociaciones empresariales y de empleadores" },
  { codigo: "94120", descripcion: "Actividades de asociaciones profesionales" },
  { codigo: "94200", descripcion: "Actividades de sindicatos de trabajadores" },
  { codigo: "94910", descripcion: "Actividades de organizaciones religiosas" },
  { codigo: "94920", descripcion: "Actividades de organizaciones políticas" },
  { codigo: "94990", descripcion: "Actividades de otras asociaciones n.c.p." },
  { codigo: "95110", descripcion: "Reparación de computadoras y equipo periférico" },
  { codigo: "95120", descripcion: "Reparación de equipos de comunicación" },
  { codigo: "95210", descripcion: "Reparación de aparatos electrónicos de consumo" },
  { codigo: "95220", descripcion: "Reparación de aparatos de uso doméstico" },
  { codigo: "95230", descripcion: "Reparación de calzado y artículos de cuero" },
  { codigo: "95240", descripcion: "Reparación de muebles y accesorios domésticos" },
  { codigo: "95290", descripcion: "Reparación de otros efectos personales y enseres domésticos" },
  { codigo: "96011", descripcion: "Lavado y limpieza de productos textiles y de piel" },
  { codigo: "96012", descripcion: "Peluquería y otros tratamientos de belleza" },
  { codigo: "96013", descripcion: "Pompas fúnebres y actividades relacionadas" },
  { codigo: "96090", descripcion: "Otras actividades de servicios no clasificadas previamente" },
  { codigo: "96092", descripcion: "Servicios n.c.p." },
  { codigo: "97000", descripcion: "Actividades de los hogares como empleadores de personal doméstico" },
  { codigo: "99000", descripcion: "Actividades de organizaciones y organismos extraterritoriales" },
];

// Obtener actividad por código
export const getActividadPorCodigo = (codigo: string): ActividadEconomica | undefined => {
  return actividadesEconomicas.find(a => a.codigo === codigo);
};

// Buscar actividades por descripción
export const buscarActividades = (termino: string): ActividadEconomica[] => {
  const terminoLower = termino.toLowerCase();
  return actividadesEconomicas.filter(a => 
    a.descripcion.toLowerCase().includes(terminoLower) ||
    a.codigo.includes(termino)
  );
};

// Actividades más comunes (para mostrar primero en selectores)
export const actividadesComunes: string[] = [
  '47111', // Venta al por menor en comercios no especializados
  '56110', // Restaurantes
  '69200', // Contabilidad y auditoría
  '69100', // Actividades jurídicas
  '62010', // Desarrollo de sistemas informáticos
  '47721', // Venta de productos farmacéuticos
  '45120', // Mantenimiento y reparación de vehículos
  '46311', // Venta al por mayor de alimentos
  '41001', // Construcción de edificios
  '70202', // Consultoría de gestión
];
