export const DTE_SCHEMA = {
  $schema: 'http://json-schema.org/draft-07/schema#',
  title: 'Esquema Oficial MH DTE',
  description: 'Esquema validado por Ministerio de Hacienda para transmisión DTE',
  type: 'object',
  oneOf: [
    { $ref: '#/definitions/FE' },
    { $ref: '#/definitions/CCFE' },
    { $ref: '#/definitions/FEXE' },
  ],
  definitions: {
    UUID: {
      type: 'string',
      pattern: '^[A-F0-9]{8}-[A-F0-9]{4}-4[A-F0-9]{3}-[89AB][A-F0-9]{3}-[A-F0-9]{12}$',
    },
    NIT: {
      type: 'string',
      pattern: '^\\d{9,14}$',
    },
    NRC: {
      type: 'string',
      pattern: '^\\d{2,8}$',
    },
    Fecha: {
      type: 'string',
      pattern: '^\\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12]\\d|3[01])$',
    },
    Hora: {
      type: 'string',
      pattern: '^([01]\\d|2[0-3]):([0-5]\\d):([0-5]\\d)$',
    },
    Moneda: {
      type: 'string',
      const: 'USD',
    },
    CuerpoDocumento: {
      type: 'array',
      minItems: 1,
      maxItems: 2000,
      items: {
        type: 'object',
        required: ['numItem', 'tipoItem', 'cantidad', 'descripcion', 'precioUni', 'montoDescu', 'ventaNoSuj', 'ventaExenta', 'ventaGravada', 'tributos'],
        properties: {
          numItem: { type: 'integer', minimum: 1, maximum: 2000 },
          tipoItem: { type: 'integer', enum: [1, 2] },
          cantidad: { type: 'number', multipleOf: 0.00000001, minimum: 0.00000001, maximum: 99999999999.99999999 },
          codigo: { type: ['string', 'null'], maxLength: 25 },
          uniMedida: { type: 'integer' },
          descripcion: { type: 'string', maxLength: 200 },
          precioUni: { type: 'number', multipleOf: 0.00000001, minimum: 0, maximum: 99999999999.99999999 },
          montoDescu: { type: 'number', multipleOf: 0.00000001, minimum: 0 },
          ventaNoSuj: { type: 'number', multipleOf: 0.00000001, minimum: 0 },
          ventaExenta: { type: 'number', multipleOf: 0.00000001, minimum: 0 },
          ventaGravada: { type: 'number', multipleOf: 0.00000001, minimum: 0 },
          tributos: {
            type: ['array', 'null'],
            items: { type: 'string', pattern: '^(20)$' },
          },
          numeroDocumento: { type: ['string', 'null'], maxLength: 30 },
          codTributo: { type: ['string', 'null'], pattern: '^(20)$' },
          psv: { type: 'number', multipleOf: 0.01, minimum: 0 },
          noGravado: { type: 'number', multipleOf: 0.01, minimum: 0 },
          ivaItem: { type: 'number', multipleOf: 0.01, minimum: 0 },
        },
      },
    },
    Resumen: {
      type: 'object',
      required: [
        'totalNoSuj',
        'totalExenta',
        'totalGravada',
        'subTotalVentas',
        'descuNoSuj',
        'descuExenta',
        'descuGravada',
        'porcentajeDescuento',
        'totalDescu',
        'totalIva',
        'tributos',
        'subTotal',
        'ivaRete1',
        'reteRenta',
        'montoTotalOperacion',
        'totalNoGravado',
        'totalPagar',
        'totalLetras',
        'saldoFavor',
        'condicionOperacion',
        'pagos',
        'numPagoElectronico',
      ],
      properties: {
        totalNoSuj: { type: 'number', multipleOf: 0.01, minimum: 0 },
        totalExenta: { type: 'number', multipleOf: 0.01, minimum: 0 },
        totalGravada: { type: 'number', multipleOf: 0.01, minimum: 0 },
        subTotalVentas: { type: 'number', multipleOf: 0.01, minimum: 0 },
        descuNoSuj: { type: 'number', multipleOf: 0.01, minimum: 0 },
        descuExenta: { type: 'number', multipleOf: 0.01, minimum: 0 },
        descuGravada: { type: 'number', multipleOf: 0.01, minimum: 0 },
        porcentajeDescuento: { type: 'number', multipleOf: 0.01, minimum: 0 },
        totalDescu: { type: 'number', multipleOf: 0.01, minimum: 0 },
        totalIva: { type: 'number', multipleOf: 0.01, minimum: 0 },
        tributos: {
          type: ['array', 'null'],
          items: {
            type: 'object',
            required: ['codigo', 'descripcion', 'valor'],
            properties: {
              codigo: { type: 'string', pattern: '^(20)$' },
              descripcion: { type: 'string', maxLength: 300 },
              valor: { type: 'number', multipleOf: 0.01, minimum: 0 },
            },
          },
        },
        subTotal: { type: 'number', multipleOf: 0.01 },
        ivaRete1: { type: 'number', multipleOf: 0.01, minimum: 0 },
        reteRenta: { type: 'number', multipleOf: 0.01, minimum: 0 },
        montoTotalOperacion: { type: 'number', multipleOf: 0.01, minimum: 0 },
        totalNoGravado: { type: 'number', multipleOf: 0.01 },
        totalPagar: { type: 'number', multipleOf: 0.01 },
        totalLetras: { type: 'string', maxLength: 200, pattern: '.*USD$' },
        saldoFavor: { type: 'number', multipleOf: 0.01, minimum: 0 },
        condicionOperacion: { type: 'integer', enum: [1, 2, 3] },
        pagos: {
          type: ['array', 'null'],
          items: {
            type: 'object',
            properties: {
              codigo: { type: 'string', pattern: '^(01|02|03|04|05|06|07|08|09|10|99)$' },
              montoPago: { type: 'number', multipleOf: 0.01, minimum: 0 },
              referencia: { type: ['string', 'null'], maxLength: 50 },
              plazo: { type: ['string', 'null'], pattern: '^(01|02|03|04|05|06|07|08|09|10|11|12)$' },
              periodo: { type: ['integer', 'null'], minimum: 1, maximum: 999 },
            },
          },
        },
        numPagoElectronico: { type: ['string', 'null'], maxLength: 100 },
      },
    },
    Extension: {
      type: ['object', 'null'],
      properties: {
        nombEntrega: { type: ['string', 'null'], maxLength: 100 },
        docuEntrega: { type: ['string', 'null'], maxLength: 25 },
        nombRecibe: { type: ['string', 'null'], maxLength: 100 },
        docuRecibe: { type: ['string', 'null'], maxLength: 25 },
        placaVehiculo: { type: ['string', 'null'], maxLength: 10 },
        observaciones: { type: ['string', 'null'], maxLength: 3000 },
      },
    },
    Apendice: {
      type: ['array', 'null'],
      maxItems: 10,
      items: {
        type: 'object',
        properties: {
          campo: { type: ['string', 'null'], maxLength: 25 },
          etiqueta: { type: ['string', 'null'], maxLength: 50 },
          valor: { type: ['string', 'null'], maxLength: 150 },
        },
      },
    },
    FE: {
      type: 'object',
      required: ['identificacion', 'emisor', 'receptor', 'cuerpoDocumento', 'resumen'],
      properties: {
        identificacion: {
          type: 'object',
          required: ['version', 'ambiente', 'tipoDte', 'numeroControl', 'codigoGeneracion', 'tipoModelo', 'tipoOperacion', 'fecEmi', 'horEmi', 'tipoMoneda'],
          properties: {
            version: { type: 'integer', const: 1 },
            ambiente: { type: 'string', enum: ['00', '01'] },
            tipoDte: { type: 'string', const: '01' },
            numeroControl: { type: 'string', pattern: '^DTE-01-[A-Z0-9]{8}-\\d{15}$' },
            codigoGeneracion: { $ref: '#/definitions/UUID' },
            tipoModelo: { type: 'integer', enum: [1, 2] },
            tipoOperacion: { type: 'integer', enum: [1, 2] },
            tipoContingencia: { type: ['integer', 'null'], enum: [1, 2, 3, 4, 5, null] },
            motivoContin: { type: ['string', 'null'], maxLength: 500 },
            fecEmi: { $ref: '#/definitions/Fecha' },
            horEmi: { $ref: '#/definitions/Hora' },
            tipoMoneda: { $ref: '#/definitions/Moneda' },
          },
        },
        documentoRelacionado: { type: ['object', 'null'] },
        emisor: {
          type: 'object',
          required: ['nit', 'nrc', 'nombre', 'codActividad', 'descActividad', 'tipoEstablecimiento', 'codEstable', 'codPuntoVenta', 'direccion', 'telefono', 'correo'],
          properties: {
            nit: { $ref: '#/definitions/NIT' },
            nrc: { $ref: '#/definitions/NRC' },
            nombre: { type: 'string', maxLength: 250 },
            codActividad: { type: 'string', pattern: '^\\d{5,6}$' },
            descActividad: { type: 'string', maxLength: 150 },
            nombreComercial: { type: ['string', 'null'], maxLength: 150 },
            tipoEstablecimiento: { type: 'string', enum: ['01', '02', '03', '04', '05'] },
            codEstable: { type: ['string', 'null'], maxLength: 10 },
            codPuntoVenta: { type: ['string', 'null'], maxLength: 15 },
            direccion: {
              type: 'object',
              required: ['departamento', 'municipio', 'complemento'],
              properties: {
                departamento: { type: 'string', pattern: '^(0[1-9]|1[0-4])$' },
                municipio: { type: 'string', pattern: '^(0[1-9]|[1-5]\\d|6[0-8])$' },
                complemento: { type: 'string', maxLength: 200 },
              },
            },
            telefono: { type: 'string', maxLength: 30, minLength: 8 },
            correo: { type: 'string', format: 'email', maxLength: 100 },
            codEstableMH: { type: ['string', 'null'], maxLength: 10 },
            codPuntoVentaMH: { type: ['string', 'null'], maxLength: 15 },
          },
        },
        receptor: {
          type: 'object',
          required: ['nombre'],
          properties: {
            tipoDocumento: { type: ['string', 'null'], enum: ['13', '36', '37', null] },
            numDocumento: { type: ['string', 'null'], maxLength: 30 },
            nombre: { type: 'string', maxLength: 250 },
            nrc: { type: ['string', 'null'], pattern: '^\\d{2,8}$' },
            codActividad: { type: ['string', 'null'], pattern: '^\\d{5,6}$' },
            descActividad: { type: ['string', 'null'], maxLength: 150 },
            direccion: {
              type: ['object', 'null'],
              properties: {
                departamento: { type: ['string', 'null'], pattern: '^(0[1-9]|1[0-4])$' },
                municipio: { type: ['string', 'null'], pattern: '^(0[1-9]|[1-5]\\d|6[0-8])$' },
                complemento: { type: ['string', 'null'], maxLength: 200 },
              },
            },
            telefono: { type: ['string', 'null'], maxLength: 30 },
            correo: { type: 'string', format: 'email', maxLength: 100 },
          },
        },
        otrosDocumentos: { type: ['object', 'null'] },
        ventaTercero: { type: ['object', 'null'] },
        cuerpoDocumento: { $ref: '#/definitions/CuerpoDocumento' },
        resumen: { $ref: '#/definitions/Resumen' },
        extension: { $ref: '#/definitions/Extension' },
        apendice: { $ref: '#/definitions/Apendice' },
      },
    },
    CCFE: {
      type: 'object',
      required: ['identificacion', 'emisor', 'receptor', 'cuerpoDocumento', 'resumen'],
      properties: {
        identificacion: {
          type: 'object',
          required: ['ambiente', 'tipoDte', 'numeroControl', 'codigoGeneracion', 'tipoModelo', 'tipoOperacion', 'fecEmi', 'horEmi', 'tipoMoneda'],
          properties: {
            version: { type: 'integer' },
            ambiente: { type: 'string', enum: ['00', '01'] },
            tipoDte: { type: 'string', const: '03' },
            numeroControl: { type: 'string', pattern: '^DTE-03-[A-Z0-9]{8}-\\d{15}$' },
            codigoGeneracion: { $ref: '#/definitions/UUID' },
            tipoModelo: { type: 'integer', enum: [1, 2] },
            tipoOperacion: { type: 'integer', enum: [1, 2] },
            tipoContingencia: { type: ['integer', 'null'], enum: [1, 2, 3, 4, 5, null] },
            motivoContin: { type: ['string', 'null'], maxLength: 500 },
            fecEmi: { $ref: '#/definitions/Fecha' },
            horEmi: { $ref: '#/definitions/Hora' },
            tipoMoneda: { $ref: '#/definitions/Moneda' },
          },
        },
        documentoRelacionado: { type: ['object', 'null'] },
        emisor: { $ref: '#/definitions/FE/properties/emisor' },
        receptor: { $ref: '#/definitions/FE/properties/receptor' },
        otrosDocumentos: { type: ['object', 'null'] },
        ventaTercero: { type: ['object', 'null'] },
        cuerpoDocumento: { $ref: '#/definitions/CuerpoDocumento' },
        resumen: { $ref: '#/definitions/Resumen' },
        extension: { $ref: '#/definitions/Extension' },
        apendice: { $ref: '#/definitions/Apendice' },
      },
    },
    FEXE: {
      type: 'object',
      required: ['identificacion', 'emisor', 'receptor', 'cuerpoDocumento', 'resumen'],
      properties: {
        identificacion: {
          type: 'object',
          required: ['ambiente', 'tipoDte', 'numeroControl', 'codigoGeneracion', 'tipoModelo', 'tipoOperacion', 'fecEmi', 'horEmi', 'tipoMoneda'],
          properties: {
            version: { type: 'integer' },
            ambiente: { type: 'string', enum: ['00', '01'] },
            tipoDte: { type: 'string', const: '11' },
            numeroControl: { type: 'string', pattern: '^DTE-11-[A-Z0-9]{8}-\\d{15}$' },
            codigoGeneracion: { $ref: '#/definitions/UUID' },
            tipoModelo: { type: 'integer', enum: [1, 2] },
            tipoOperacion: { type: 'integer', enum: [1, 2] },
            tipoContingencia: { type: ['integer', 'null'], enum: [1, 2, 3, 4, 5, null] },
            motivoContin: { type: ['string', 'null'], maxLength: 500 },
            fecEmi: { $ref: '#/definitions/Fecha' },
            horEmi: { $ref: '#/definitions/Hora' },
            tipoMoneda: { $ref: '#/definitions/Moneda' },
          },
        },
        documentoRelacionado: { type: ['object', 'null'] },
        emisor: { $ref: '#/definitions/FE/properties/emisor' },
        receptor: { $ref: '#/definitions/FE/properties/receptor' },
        otrosDocumentos: { type: ['object', 'null'] },
        ventaTercero: { type: ['object', 'null'] },
        cuerpoDocumento: { $ref: '#/definitions/CuerpoDocumento' },
        resumen: { $ref: '#/definitions/Resumen' },
        extension: { $ref: '#/definitions/Extension' },
        apendice: { $ref: '#/definitions/Apendice' },
      },
    },
  },
} as const;
